---
swagger: '2.0'
info:
  title: Udaan18 Text Messaging API
  description: ''
  version: '1.0'
schemes:
- http
- https
consumes:
- application/json
paths:
  "/events/{id}":
    get:
      tags:
      - events
      summary: Returns details of a particular event
      description: ''
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - in: path
        name: id
        description: The `id` of the event
        required: true
        type: string
      responses:
        '200':
          description: The details of the event
          schema:
            "$ref": "#/definitions/event"
        '401':
          description: Unauthorized. Likely due to a bad or expired token.
  "/events/{eventId}/participants":
    get:
      tags:
      - participants
      summary: Returns all the participants in an event.
      description: ''
      parameters:
        - in: path
          name: eventId
          required: true
          type: string
          description: The `id` of the event.
      responses:
        '200':
          description: A list of participants in the event.
          schema:
            "$ref": "#/definitions/participants"
        '401':
          description: Unauthorized. Likely due to a bad or expired token.
        '404':
          description: Event not found.
  "/events/{eventId}/participants/promote":
    post:
      tags:
      - participants
      summary: Promote participants to next round
      parameters:
      - in: path
        name: eventId
        description: 'The `id` of the event.'
        required: true
        type: string
      - in: body
        name: body
        description: ''
        required: true
        schema:
          "$ref": '#/definitions/promotionData'

      responses:
        '200':
          description: Promoted successfully
definitions:
  event:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      type:
        type: string
      department:
        type: string
      currentRound:
        type: integer
        format: int32
      teamSize:
        type: integer
        format: int32
  participant:
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
      phone:
        type: string
      registrationDate:
        type: string
      round:
        type: integer
        format: int32
      deliveryStatus:
        type: string
  participants:
    type: array
    items:
      "$ref": "#/definitions/participant"
  promotionData:
    type: object
    properties:
      date:
        type: string
      time:
        type: string
      venue:
        type: string
      participantIds:
        type: array
        items:
          type: integer
